
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:5 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Program Files/Python314/Scripts/"
      - "C:/Program Files/Python314/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/"
      - "C:/Program Files/Microsoft VS Code/bin/"
      - "D:/MiKTeX/miktex/bin/x64/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/PyManager/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/VSCodium/bin/"
      - "C:/Users/julia/.local/bin/"
      - "C:/Users/julia/scoop/shims/"
      - "C:/Users/julia/.elan/bin/"
      - "C:/Users/julia/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/julia/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/julia/.dotnet/tools/"
      - "C:/Users/julia/AppData/Local/JetBrains/Toolbox/scripts/"
      - "C:/Users/julia/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "C:/Users/julia/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "C:/Program Files/CodeBlocks/MinGW/bin/"
    searched_directories:
      - "C:/Program Files/Python314/Scripts/mingw32-make.exe.com"
      - "C:/Program Files/Python314/Scripts/mingw32-make.exe"
      - "C:/Program Files/Python314/mingw32-make.exe.com"
      - "C:/Program Files/Python314/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/mingw32-make.exe"
      - "C:/Program Files/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft VS Code/bin/mingw32-make.exe"
      - "D:/MiKTeX/miktex/bin/x64/mingw32-make.exe.com"
      - "D:/MiKTeX/miktex/bin/x64/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files/PyManager/mingw32-make.exe.com"
      - "C:/Program Files/PyManager/mingw32-make.exe"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe.com"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/mingw32-make.exe.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/VSCodium/bin/mingw32-make.exe.com"
      - "C:/Program Files/VSCodium/bin/mingw32-make.exe"
      - "C:/Users/julia/.local/bin/mingw32-make.exe.com"
      - "C:/Users/julia/.local/bin/mingw32-make.exe"
      - "C:/Users/julia/scoop/shims/mingw32-make.exe.com"
      - "C:/Users/julia/scoop/shims/mingw32-make.exe"
      - "C:/Users/julia/.elan/bin/mingw32-make.exe.com"
      - "C:/Users/julia/.elan/bin/mingw32-make.exe"
      - "C:/Users/julia/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/julia/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/julia/AppData/Local/GitHubDesktop/bin/mingw32-make.exe.com"
      - "C:/Users/julia/AppData/Local/GitHubDesktop/bin/mingw32-make.exe"
      - "C:/Users/julia/.dotnet/tools/mingw32-make.exe.com"
      - "C:/Users/julia/.dotnet/tools/mingw32-make.exe"
      - "C:/Users/julia/AppData/Local/JetBrains/Toolbox/scripts/mingw32-make.exe.com"
      - "C:/Users/julia/AppData/Local/JetBrains/Toolbox/scripts/mingw32-make.exe"
      - "C:/Users/julia/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/mingw32-make.exe.com"
      - "C:/Users/julia/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/mingw32-make.exe"
      - "C:/Users/julia/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/mingw32-make.exe.com"
      - "C:/Users/julia/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "C:/Program Files/CodeBlocks/MinGW/bin/mingw32-make.exe.com"
      - "C:/Program Files/CodeBlocks/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Python314\\Scripts\\"
        - "C:\\Program Files\\Python314\\"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Microsoft VS Code\\bin"
        - "D:\\MiKTeX\\miktex\\bin\\x64\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\PyManager\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\VSCodium\\bin"
        - "C:\\Users\\julia\\.local\\bin"
        - "C:\\Users\\julia\\scoop\\shims"
        - "C:\\Users\\julia\\.elan\\bin"
        - "C:\\Users\\julia\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\julia\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\julia\\.dotnet\\tools"
        - "C:\\Users\\julia\\AppData\\Local\\JetBrains\\Toolbox\\scripts"
        - "C:\\Users\\julia\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin"
        - "c:\\Users\\julia\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
...
