name: C/C++ CI

on:
  push:
    branches: [ "main", "revisada" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Permite que todos los trabajos finalicen, incluso si uno falla
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cxx_compiler: g++
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cxx_compiler: clang++
          - os: windows-latest
            compiler: msvc
            # En Windows, CMake detecta MSVC autom√°ticamente

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      working-directory: ./build
      run: ctest -C Release --output-on-failure
